from enum import Enum

class GameStates(Enum):
	PLAYER_TURN = 1
	ENEMY_TURN = 2
	PLAYER_DEAD = 3
	SHOW_INVENTORY = 4
	DROP_INVENTORY = 5
	TARGETING = 6
	DIRECTIONAL_TARGETING = 7
	LEVEL_UP = 8
	CHARACTER_SCREEN = 9
	VENDOR_SELECT = 10
	VENDOR_BUY = 11
	VENDOR_SELL = 12